// <auto-generated/>
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly:
    SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Domain Term",
        Scope = "type", Target = "~T:Mmu.Mlh.LanguageExtensions.Areas.Types.Options.Option`1")]
[assembly:
    SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Domain Term",
        Scope = "type", Target = "~T:Mmu.Mlh.LanguageExtensions.Areas.Types.Options.Option")]